# Generated by Django 5.0.2 on 2024-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_backgrounds/'),
        ),
    ]
